In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Wine_Quality_Data.csv")

In [3]:
df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [19]:
#Suggested = 2 - 5%
sample = df["citric_acid"].sample(frac = 0.03)
sample

449     0.69
3831    0.31
5539    0.37
1690    0.43
1109    0.43
        ...
6289    0.32
3645    0.43
1774    0.40
5573    0.52
4439    0.33
Name: citric_acid, Length: 195, dtype: float64

In [20]:
#scientific library

from scipy import stats

In [21]:
#for finding the one sample t test 
t_test,p_value = stats.ttest_1samp(sample,df["citric_acid"].mean())

In [22]:
t_test #t_test refer the above formula

0.546502038684605

In [23]:
p_value # based on the t_test value predefined probability table gets refered.

0.5853488721129441

In [ ]:
if p_value < 0.04:
    print("H0 reject null hypothesis, Ha accepts alternate hypothesis, data is not normally distributed")
else:
    print("H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed")

In [25]:
for i in range (31):
    sample = df["citric_acid"].sample(frac = 0.03)
    t_test,p_value = stats.ttest_1samp(sample,df["citric_acid"].mean())
    print (t_test, p_value)
    if p_value < 0.04:
        print("H0 reject null hypothesis, Ha accepts alternate hypothesis, data is not normally distributed")
    else:
        print("H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed")

0.3660087726167156 0.7147573390946934
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.5656684738820806 0.5722728344636545
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.14662775874567652 0.8835780995294744
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.3754157843945633 0.7077614086730831
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.3174958006122747 0.7512088796320567
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-1.3920387332281117 0.16550441926919038
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-2.024937178059616 0.04424433351017862
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.2797006206394885 0.7800051892259554
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.9997711828125205 0.31866663292311714
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.5041165490336438 0.614751509162113
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-1.4725300702877215 0.14249828484406218
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
1.3117823243679603 0.19114378434398355
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-1.097689525103096 0.2737006374077914
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.636954929982054 0.5249051078107982
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.7881881642773328 0.43154868084410514
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.019601344180627374 0.9843815364708186
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.7339846947798908 0.46384420775426605
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.48717020039255005 0.6266877251974662
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.4138784027589501 0.6794203520322639
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.8019221577322417 0.4235791779592366
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.6949683926562911 0.4879066391913357
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-2.5134792759767723 0.012768297269590712
H0 reject null hypothesis, Ha accepts alternate hypothesis, data is not normally distributed
-0.021857123935752554 0.9825843910566732
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.3104570471163886 0.7565466985771943
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.08943595235390546 0.9288277156834679
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-0.06974159320069144 0.9444711711920426
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-1.939477579645962 0.05389345898396202
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.40116999970195516 0.6887364837800436
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
-2.038394084533693 0.042867583951730986
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.9930554374483094 0.321919929113677
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed
0.6527823010794066 0.5146694360445406
H0 accept null hypothesis, Ha rejects alternate hypothesis, data is normally distributed